---
- name: Post Cluster
  hosts: localhost
  vars:
    kubeconfig: "{{ working_dir }}/install/{{ ocp_cluster.name }}/auth/kubeconfig"
  connection: local
  become: false
  gather_facts: false
  tags:
    - post_cluster
  tasks:
    - debug:
        msg: "Post Install Cluster Configuration"

    - name: Configure Argo Application for Cluster
      include_role:
        name: configure-gitops


